name: Twilio SMS
  # You may pin to the exact commit or the version.
  # uses: twilio-labs/actions-sms@d1488bc77f2cc44182fb444073326ccc715103b0
uses: twilio-labs/actions-sms@v1
with:
    # Phone number in your Twilio account to send the SMS from
    fromPhoneNumber: "+14752553915"
    # Phone number to send the SMS to
    toPhoneNumber: "+989138549727"
    # The message you want to send
    message: "New Branch Update!"
    # A Twilio Account SID. Can alternatively be stored in environment
    TWILIO_ACCOUNT_SID: "AC9729f49a4f0e8bf8e760513bd0dae0d4"
    # A Twilio API Key. Can alternatively be stored `in environment
    TWILIO_API_KEY: "a4260f4732b3eb9a0fbefe223c1a4dca"
